site_name: Carina
pages:
    - Overview: index.md
    - Getting started: getting_started.md
    - Project structure: project_structure.md
    - Configuration: configuration.md
    - Execution: execution.md
    - Automation:
      - Web automation: automation/web.md
      - Mobile automation: automation/mobile.md
      - API automation: automation/api.md
    - Dataproviders: dataproviders.md
    - Security: security.md
    - Contribution: contribution.md
    - Release notes: releases.md
    - Proxy: proxy.md
theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/carina
repo_name: Github
