site_name: Carina
pages:
    - Overview: index.md
    - Getting started: getting_started.md
    - Project structure: project_structure.md
    - Configuration: configuration.md
    - Execution: execution.md
    - Automation:
      - Web: automation/web.md
      - Mobile: automation/mobile.md
      - API: automation/api.md
    - Advanced:
      - Database: advanced/database.md
      - DataProvider: advanced/dataprovider.md
      - Program flow: advanced/debug_entry_point.md
      - Driver: advanced/driver.md
      - Localization: advanced/localization.md
      - Proxy: advanced/proxy.md
      - Security: advanced/security.md
    - Cucumber: cucumber.md
    - Contribution: contribution.md
theme:
  name: 'material'
repo_url: https://github.com/qaprosoft/carina
repo_name: Github
